---
all:
  children:
    ios_switches:
      hosts:
        campus1:
          ansible_host: "54.162.84.190"
          # ansible_port: 22022
    nxos_switches:
      hosts:
        dc1:
          ansible_host: "10.10.20.58"
          # ansible_port: 22022
...
