---
all:
  children:
    ios_switches:
      hosts:
        R1:
          ansible_host: "54.162.84.190"
          # ansible_port: 22022
    nxos_switches:
      hosts:
        R2:
          ansible_host: "54.162.84.191"
          # ansible_port: 22022
...
