---
all:
  children:
    ios_switches:
      hosts:
        sw2:
          ansible_host: "10.0.10.2"
        sw4:
          ansible_host: "10.0.10.4"
    nxos_switches:
      hosts:
        sw3:
          ansible_host: "10.0.10.3"
...
