---
- name: "Build Globomantics network in NetBox"
  hosts: "netbox_servers"
  tasks:

    # REST API documentation (it's very good):
    # http://netbox1:8000/api/docs/
    - include_tasks: "tasks/{{ taskname }}.yml"
      loop:
        - "org"
        - "device"
        - "ipam"
        - "circuit"
      loop_control:
        loop_var: "taskname"
...
