---
all:
  vars:
    ansible_python_interpreter: "/usr/bin/env python"
  children:
    netbox_servers:
      vars:
        ansible_connection: "ansible.builtin.local"
      hosts:
        netbox1:
...
