---
all:
  vars:
    ansible_python_interpreter: "/usr/bin/env python"
    ansible_connection: "local"
  children:
    ios_routers:
      vars:
        ansible_connection: "ansible.netcommon.network_cli"
        ansible_network_os: "ios"
        ansible_user: "{{ ios_username }}"
        ansible_password: "{{ ios_password }}"
      hosts:
        R1:
          ipsec_src_intf: "GigabitEthernet1"
          ansible_host: "35.172.59.61"

    # You can use this placeholder to start at the "deploy_pan" stage
    # pan_aws:
      # hosts:
        # PAN_VM1:
          # ansible_host: "mgmt public IP goes here"
          # ipsec_endpoint: "vpn public IP goes here"
...
