---
- hosts: localhost
  connection: local
  vars_files:
    - "vault.yml"
  tasks:
    - name: "Search for Palo Alto NGFW images"
      amazon.aws.ec2_ami_info:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        image_id: "ami-04d797af2d3326de3"  # PA-VM 9.1.6
        # filters: name=PA-VM-AWS*
      register: pan
    - debug: var=pan

    - name: "Create security groups"
      amazon.aws.ec2_group:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        name: "PAN_management"
        description: "Allow SSH and HTTPS for PAN NGFWs"  # required!
        vpc_id: "vpc-7d5a7b1b"  # Ansible
        region: "us-east-1"
        rules:
          - rule_desc: "SSH"
            proto: "tcp"
            from_port: 22
            to_port: 22
            cidr_ip: "0.0.0.0/0"
          - rule_desc: "HTTPS"
            proto: "tcp"
            from_port: 443
            to_port: 443
            cidr_ip: "0.0.0.0/0"
      register: pan
    - debug: var=pan

    - name: "Create new ENIs"
      amazon.aws.ec2_eni:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        name: "{{ item.name }}"
        subnet_id: "{{ item.subnet_id }}"
        private_ip_address: "{{ item.private_ip_address }}"
        security_groups: "{{ item.security_groups }}"
      loop:
        - name: "Management"
          subnet_id: "subnet-3045491d"  # existing VPC public subnet
          private_ip_address: "10.125.0.77"
          security_groups: ["PAN_management"]
        - name: "Servers"
          subnet_id: "subnet-a645498b"  # existing VPC private subnet
          private_ip_address: "10.125.1.77"
          security_groups: ["PAN_management"]  # TODO
      loop_control:
        label: "{{ item.name }}: {{ item.private_ip_address }}"
      register: pan
    - debug: var=pan

    - name: "Extract ENI IDs from results"
      set_fact:
        enis: "{{ pan.results | map(attribute='interface.id') | list }}"
    - debug: var=enis

    - name: "Deploy PAN NGFW EC2 instance"
      amazon.aws.ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        image: "ami-04d797af2d3326de3"
        region: "us-east-1"
        instance_type: "m4.large"
        instance_tags:
          Name: "globoPAN"
        exact_count: 1  # needed for idempotence
        count_tag:
          Name: "globoPAN"
        network_interfaces: "{{ enis }}"
        volumes:
          - device_name: "/dev/xvda"
            volume_type: "gp2"
            volume_size: 60
            delete_on_termination: true
        wait: true
        wait_timeout: 60
        key_name: "EC2-key-pair"
      register: ec2
    - debug: var=ec2

    - fail:

    - name: "Add new EC2 instance to Ansible inventory"
      add_host:
        name: "PA-VM1"
        groups: "pa_aws"
        ansible_host: "{{ ec2.tagged_instances[0].public_ip }}"

- hosts: pa_aws
  connection: local
  vars_files:
    - "vault.yml"
  tasks:
    - name: "Define PAN NGFW credentials"
      set_fact:
        pan_creds:
          username: "{{ pan_username }}"
          password: "{{ pan_password }}"
          ip_address: "{{ ansible_host }}"
    - debug: var=pan_creds

    - name: "Update PAN NGFW admin password"
      paloaltonetworks.panos.panos_admpwd:
        ip_address: "{{ ansible_host }}"
        key_filename: "/home/centos/personalprivkey.pem"  # FQFN needed
        username: "{{ pan_creds.username }}"
        newpassword: "{{ pan_creds.password }}"
      register: "admin_pass"
      until: "'Configuration committed successfully' in admin_pass.stdout"
      retries: 30
      delay: 30  # 30 * 30 = 900 seconds = 15 minutes total
    - debug: var=admin_pass

    - name: "Wait for PA NGFW REST API to respond"
      paloaltonetworks.panos.panos_check:
        provider: "{{ pan_creds }}"
        interval: 5
        timeout: 60
      register: pan_check
    - debug: var=pan_check
