---
- hosts: localhost
  connection: local
  vars_files:
    - "vault.yml"
  tasks:
    - name: "Create new ENI"
      amazon.aws.ec2_eni:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        private_ip_address: "10.125.0.77"
        subnet_id: "subnet-3045491d"
        source_dest_check: false  # modified only, not create
        description: "OUTSIDE"
        security_groups:
          - "securityPAN"
      register: pan
    - debug: var=pan
