---
- hosts: localhost
  connection: local
  tasks:
    - set_fact:
        pan_creds:
          ip_address: "54.161.83.144"
          username: "admin"
          password: "globoPass123!"

    # https://paloaltonetworks.github.io/pan-os-ansible/
    - name: "Configure VPN underlay interface and zone"
      paloaltonetworks.panos.panos_interface:
        provider: "{{ pan_creds }}"
        if_name: "ethernet1/1"
        comment: "VPN underlay"
        zone_name: "vpn"
        create_default_route: true
        enable_dhcp: true

    - name: "Configure server interface and zone"
      paloaltonetworks.panos.panos_interface:
        provider: "{{ pan_creds }}"
        if_name: "ethernet1/2"
        comment: "Servers"
        zone_name: "servers"
        create_default_route: false
        enable_dhcp: true

    - name: "Configure IKE gateway"
      paloaltonetworks.panos.panos_ike_gateway:
        provider: "{{ pan_creds }}"
        name: "IKE_GW_GloboHQ"
        version: "ikev2"
        interface: "ethernet1/1"
        peer_ip_value: "203.0.113.1"
        pre_shared_key: "globoPass1123!"
        ikev2_crypto_profile: "Suite-B-GCM-256"  # built-in
        liveness_check_interval: 5
        enable_passive_mode: true
        enable_liveness_check: true
        enable_nat_traversal: true

    - name: "Configure IPsec tunnel interface"
      paloaltonetworks.panos.panos_tunnel:
        provider: "{{ pan_creds }}"
        if_name: "tunnel.100"
        zone_name: "globo"
        ip: ["10.1.1.1/24"]
        comment: "IPsec tunnel to Globomantics HQ"

    - name: "Configure IPsec tunnel parameters"
      paloaltonetworks.panos.panos_ipsec_tunnel:
        provider: "{{ pan_creds }}"
        name: "IPsec_Tunnel_GloboHQ"
        tunnel_interface: "tunnel.100"
        ak_ike_gateway: "IKE_GW_GloboHQ"
        ak_ipsec_crypto_profile: "Suite-B-GCM-256"  # built-in

    - name: "Permit HTTP from GloboHQ to cloud servers"
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ pan_creds }}"
        rule_name: "Eng_HTTP"
        description: "Globo engineering to web server"
        source_zone: ["globo"]
        source_ip: ["198.51.100.0/24"]
        destination_zone: ["servers"]
        service: ["service-http"]  # built-in service for TCP 80 and 8080
        location: "top"
        action: "allow"

    - name: "Commit changes"
      paloaltonetworks.panos.panos_commit_firewall:
        provider: "{{ pan_creds }}"
        description: "Ansible initial provisioning complete"
