---
all:
  vars:
    ansible_python_interpreter: "/usr/bin/env python"
    ansible_connection: "ansible.builtin.local"
  children:
    ios_routers:
      vars:
        ansible_connection: "ansible.netcommon.network_cli"
        ansible_network_os: "ios"
        ansible_user: "{{ ios_username }}"
        ansible_password: "{{ ios_password }}"
      hosts:
        R1:
          # ansible_host: "192.168.10.1"
          ansible_host: "54.162.84.190"
          ipsec_src_intf: "GigabitEthernet1"
...
