---
- name: "Configure VLANs and SVIs on switches"
  hosts: "all"
  collections:
    - "ansible.netcommon"
  tasks:
    - name: "Store template path per device type"
      set_fact:
        template_path: "templates/{{ ansible_network_os }}_vlans.j2"

    - name: "Apply config updates from jinja2 templates"
      cli_config:
        config: "{{ lookup('template', template_path) }}"
      register: "vlan_updates"
      notify: "changes_occurred"

  handlers:
    - name: "Print config changes when updates occurred"
      listen: "changes_occurred"
      debug:
        msg: >- 
          {{ vlan_updates['diff'] if 'diff' in vlan_updates
          else vlan_updates['commands'] }}

    - name: "Print on-box when updates occurred and feature is available"
      listen: "changes_occurred"
      debug:
        msg: "{{ vlan_updates['diff'].split('\n') }}"
      when: "'diff' in vlan_updates"

    - name: "Print commands sent to device when updates occurred"
      listen: "changes_occurred"
      debug:
        var: "vlan_updates.commands"
      when: "'commands' in vlan_updates"

    - name: "Save configuration when updates occurred"
      listen: "changes_occurred"
      cli_command:
        command: "copy running-config startup-config"
...
