---
- name: "Create router WAN interface"
  netbox.netbox.netbox_device_interface:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      device: "Edge Router"
      name: "Serial0/0"
      type: "t3"  # aka DS3
      mtu: 1500
      enabled: true
      mgmt_only: false

- name: "Create Verizon ISP"
  netbox.netbox.netbox_provider:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "Verizon"
      asn: 701
      account: "GLOBO123"
      portal_url: "https://business.verizon.com"

- name: "Create DS3 circuit type"
  netbox.netbox.netbox_circuit_type:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "DS3"

- name: "Create Verizon uplink circuit"
  netbox.netbox.netbox_circuit:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      cid: "XYZ987"
      provider: "Verizon"
      circuit_type: "DS3"
      status: "active"
      install_date: "2021-01-04"
      commit_rate: 44736

- name: "Create circuit termination (Z)"
  netbox.netbox.netbox_circuit_termination:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      circuit: "XYZ987"
      port_speed: 44736
      term_side: "Z"  # A: provider / Z: customer
      site: "Americas HQ"

- name: "Create cable from router WAN port to circuit termination"
  netbox.netbox.netbox_cable:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      termination_a_type: "dcim.interface"
      termination_a:
        device: "Edge Router"
        name: "Serial0/0"
      termination_b_type: "circuits.circuittermination"
      termination_b:
        name: "XYZ987"
...
