---
- name: "Create region"
  netbox.netbox.netbox_region:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ location.region }}"

- name: "Create HQ site"
  netbox.netbox.netbox_site:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ location.hq }}"
      status: "active"
      region: "{{ location.region }}"
      asn: 65001
      time_zone: "America/New York"
      physical_address: "123 Main Street"
      contact_name: "John Smith"
      contact_email: "john@globomantics.com"
...
