---
- name: "Create data center racks"
  netbox.netbox.netbox_rack:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ item }}"
      site: "{{ location.hq }}"
      status: "active"
      type: "4-post cabinet"
      width: 19
      u_height: 42
      desc_units: true
  loop:
    - "Row1RackA"
    - "Row1RackB"

- name: "Create manufacturers"
  netbox.netbox.netbox_manufacturer:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ item }}"
  loop: ["Cisco", "Arista"]

# Useful tip: use the "part_number" to store the ansible_network_os
- name: "Create device types"
  netbox.netbox.netbox_device_type:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      slug: "{{ item.slug }}"
      model: "{{ item.slug }}"
      manufacturer: "{{ item.manufacturer }}"
      u_height: "{{ item.u_height }}"
      is_full_depth: true
  loop:
    - manufacturer: "Cisco"
      slug: "ISR-4451"
      part_number: "ios"
      u_height: 2
    - manufacturer: "Cisco"
      slug: "C9300-24T"
      part_number: "ios"
      u_height: 1
    - manufacturer: "Cisco"
      slug: "N9K-9372TX"
      part_number: "nxos"
      u_height: 1
    - manufacturer: "Arista"
      slug: "DCS-7050QX-32S"
      part_number: "eos"
      u_height: 1
  loop_control:
    label: "{{ item.manufacturer }} {{ item.slug }}"

- name: "Create device roles"
  netbox.netbox.netbox_device_role:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ item.name }}"
      color: "{{ item.color }}"
  loop:
    - name: "Router"
      color: "FF0000"  # red
    - name: "Switch"
      color: "0000FF"  # blue
  loop_control:
    label: "{{ item.name }}"

- name: "Create devices"
  netbox.netbox.netbox_device:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ item.name }}"
      device_type: "{{ item.device_type }}"
      device_role: "{{ item.device_role }}"
      rack: "{{ item.rack }}"
      position: "{{ item.position }}"
      face: "front"
      site: "{{ location.hq }}"
  loop:
    - name: "R1"
      device_type: "ISR-4451"
      device_role: "Router"
      rack: "Row1RackA"
      position: 1
    - name: "S2"
      device_type: "C9300-24T"
      device_role: "Switch"
      rack: "Row1RackA"
      position: 5
    - name: "S3"
      device_type: "N9K-9372TX"
      device_role: "Switch"
      rack: "Row1RackB"
      position: 1
    - name: "S4"
      device_type: "DCS-7050QX-32S"
      device_role: "Switch"
      rack: "Row1RackB"
      position: 3
  loop_control:
    label: "{{ item.name }} - {{ item.device_type }}"
...
